version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: Serverplataforma2001!
      MYSQL_DATABASE: plataformaCalidad
      MYSQL_USER: plataformaCalidadUser
      MYSQL_PASSWORD: Usercalidad2001!
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - /root/PlataformaCalidad/media-files:/media-files

volumes:
  mysql-data: